# Generated by Django 4.1.9 on 2023-05-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xauthapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='videoUrl',
            field=models.URLField(default=None),
        ),
    ]
