# Generated by Django 4.1.9 on 2023-05-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xauthapp', '0002_movie_description_movie_duration_movie_videourl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Account',
        ),
    ]
